### ISSUE TITLE
Hamburger Menu Button

### ISSUE THREAD

**Issue by sebastianvburlacu** [JugglerX/gatsby-serif-theme#1]
The hamburger menu is not working when clicked, i presume a sliding window with the menu items should appear when clicking on it.

**Comment by JugglerX** [comment]
Hi mate, thanks for bringing this my attention. I've pushed a quick fix which appears to make the mobile menu work. This was pretty quick, I'll have to test it more in a few days. Might make even more sense to replace this with a react library like react-burger-menu or something. The code driving the current mobilemenu really revolved around vanilla js and class switches, so it did not port very well.

**Comment by sebastianvburlacu** [comment]
No problem, I too think that using a react library would probably be the nicest way. Cheers!
