### ISSUE TITLE
node-sass missing- resolved. 

### ISSUE THREAD

**Issue by derekregent** [JugglerX/gatsby-serif-theme#6]
Is something missing? I tried a couple times and still had errors making a new website using this theme since directories were missing: 
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node":

Snapshot follows- or see the attached .pdf for entire output: 

daniel@daniel-ubuntu:~$ gatsby new serif  https://github.com/JugglerX/gatsby-serif-theme.git
info Creating new site from git: https://github.com/JugglerX/gatsby-serif-theme.git

Cloning into 'serif'...
remote: Enumerating objects: 520, done.
remote: Total 520 (delta 0), reused 0 (delta 0), pack-reused 520
Receiving objects: 100% (520/520), 1.34 MiB | 5.68 MiB/s, done.
success Created starter directory layout
info Installing packages...

> node-sass@4.11.0 install /home/daniel/serif/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-x64-72_binding.node": 

HTTP error 404 Not Found
[Uploading Serif starter failed.pdf…]()

**Comment by derekregent** [comment]
This problem occurred for me in Ubuntu. This should be in the readme: 
1. 
Install Gatsby per official tutorial
2. 
Get folder for theme: 
gatsby new serif https://github.com/JugglerX/gatsby-serif-theme.git

2b.
if there are errors with node-sass preinstall it and then rerun 2.: 
npm install node-sass

3. Deploy site
cd serif
gatsby develop

Thanks!!

**Comment by netlander** [comment]
Should be made clear in the readme.

**Comment by JugglerX** [comment]
Thank you all for leaving helpful hints for other people.

`node-sass` is listed as a dependancy in the package.json - so all you should need to do is run `npm install` and then run Gatsby. It does not necessarily need to be installed globally.

There are various reasons why node-sass might fail which depend on your individual environment. Often re-running `npm install` can fix it, or as you have suggested installing it globally might also resolve the issue.

There is no reason to include every installation edge case in the readme. I'm glad you have solved the problem and this issue will be helpful for others in the future

**Comment by netlander** [comment]
The installation instructions in the readme are incorrect.

**Comment by JugglerX** [comment]
I just tried installing it, i had to run `npm run start` instead of `gatsby develop` - but that has nothing to do with node sass... `gatsby develop` would probably have worked if I had it installed globally. 

Honestly you couldent sound any more arrogant and entitled. If you think there is a problem try doing a PR. updating the README has to be the easiest PR you could do...
