### ISSUE TITLE
How to change cover picture?

### ISSUE THREAD

**Issue by OGALI** [JugglerX/gatsby-serif-theme#7]
Not able to find how to change the cover picture on the home page. undraw_taking_notes_tjaf.svg

**Comment by JugglerX** [comment]
You can update the background image in the scss file _home.scss - see this line https://github.com/JugglerX/gatsby-serif-theme/blob/master/src/scss/pages/_home.scss#L2

**Comment by OGALI** [comment]
thank you worked!
